export const actionTypes = {
  USER_FETCH_REQUEST: "USER_FETCH_REQUEST",
  USER_FETCH_SUCCESS: "USER_FETCH_SUCCESS",
  USER_FETCH_FAILED: "USER_FETCH_FAILED",
  INCREASE_COUNTER_A: "INCREASE_COUNTER_A",
  INCREASE_COUNTER_B: "INCREASE_COUNTER_B",
  SWAP_ACADEMY_ADDRESS: "SWAP_ACADEMY_ADDRESS",
  CHANGE_ACADEMY_NAME: "CHANGE_ACADEMY_NAME",
  CHANGE_THEME: "CHANGE_THEME",
};
